apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- route.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml

commonLabels:
  app: django-backend
  app.kubernetes.io/name: django-backend
  app.kubernetes.io/part-of: web-applications

namespace: django-backend
