apiVersion: v1
kind: Secret
metadata:
  name: django-backend-ssh-secret
  namespace: django-backend
  labels:
    app: django-backend-ssh
    app.kubernetes.io/name: django-backend-ssh
    app.kubernetes.io/part-of: web-applications
  annotations:
    argocd.argoproj.io/sync-wave: "10"
type: Opaque
data:
  # Password: DjangoDev@2024 (base64 encoded)
  password: RGphbmdvRGV2QDIwMjQ=
