apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- route.yaml
- loadbalancer.yaml

commonLabels:
  app: ssh-access
  app.kubernetes.io/name: ssh-access
  app.kubernetes.io/part-of: rosa-deployment

namespace: ssh-access
