apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ssh-bastion-route
  namespace: ssh-access
  labels:
    app: ssh-bastion
  annotations:
    haproxy.router.openshift.io/timeout: 5m
spec:
  to:
    kind: Service
    name: ssh-bastion-service
  port:
    targetPort: ssh
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
