apiVersion: v1
kind: Service
metadata:
  name: vue-frontend-service
  namespace: vue-frontend
  labels:
    app: vue-frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: vue-frontend
