apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-cluster-admin
  labels:
    app.kubernetes.io/name: argocd-rbac
    app.kubernetes.io/part-of: openshift-gitops
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
- kind: ServiceAccount
  name: openshift-gitops-argocd-server
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-dex-server-cluster-admin
  labels:
    app.kubernetes.io/name: argocd-rbac
    app.kubernetes.io/part-of: openshift-gitops
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-dex-server
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
