apiVersion: v1
kind: Secret
metadata:
  name: github-repo-apps
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/rich-p-ai/rosa.git
  name: github-rosa-repo
