apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rosa-web-applications
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: rosa-web-applications
    app.kubernetes.io/part-of: rosa-deployment
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rich-p-ai/apps.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
      include: "apps/*"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .spec.template.spec.containers[]?.resources
