apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- route.yaml
- configmap.yaml
- secret.yaml

commonLabels:
  app: nodejs-backend
  app.kubernetes.io/name: nodejs-backend
  app.kubernetes.io/part-of: web-applications

namespace: nodejs-backend
