apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend-ssh-service
  namespace: nodejs-backend
  labels:
    app: nodejs-backend-ssh
    app.kubernetes.io/name: nodejs-backend-ssh
    app.kubernetes.io/part-of: web-applications
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  type: ClusterIP
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  selector:
    app: nodejs-backend-ssh
