apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- react-frontend
- vue-frontend
- angular-frontend
- nodejs-backend
- django-backend
- ssh-access

commonLabels:
  app.kubernetes.io/part-of: web-applications
  app.kubernetes.io/managed-by: argocd

namespace: default
