apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: react-ssh-scc-binding
  namespace: react-frontend
  labels:
    app: react-frontend-ssh
    app.kubernetes.io/name: react-frontend-ssh
    app.kubernetes.io/part-of: web-applications
subjects:
- kind: ServiceAccount
  name: react-frontend-ssh-sa
  namespace: react-frontend
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:react-ssh-scc
  apiGroup: rbac.authorization.k8s.io
