apiVersion: v1
kind: ServiceAccount
metadata:
  name: react-frontend-ssh-sa
  namespace: react-frontend
  labels:
    app: react-frontend-ssh
    app.kubernetes.io/name: react-frontend-ssh
    app.kubernetes.io/part-of: web-applications
